name: telegram message
on: [check_run,check_suite,create,delete,deployment,deployment_status,fork,gollum,issue_comment,issues,label,milestone,page_build,project,project_card,project_column,public,pull_request,pull_request_review,pull_request_review_comment,pull_request_target,push,registry_package,release,status,watch,workflow_run]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.tg_chat }}
        token: ${{ secrets.tg_token }}
        args: The ${{ github.event_name }} event was triggered.